Revert "target-alpha: Add vector implementation for CMPBGE"
This reverts commit 7290c252fc077b523b0541de789d30a378202830.

Unfortunately the SSE2 code here fails to compile on some versions
of gcc:
 target-alpha/int_helper.c:77:24: error: invalid operands to binary >=
 (have '__vector(16) unsigned char' and '__vector(16) unsigned char')

Signed-off-by: Peter Maydell <peter.maydell@linaro.org>